### ISSUE TITLE
Adventure crash - Texture Atlas '...' cannot be found.

### ISSUE THREAD

**Issue by kosciukus** [robovm/robovm-samples#17]
Hi,
I'm trying to run Adventure sample. When i do it with ''./gradlew launchIPadSimulator --stacktrace"

I got warnings "Texture Atlas '(Environment)' cannot be found" on every texture and then "java.lang.IndexOutOfBoundsException: index = 0, size = 0" which is understandable because of empty texture array. Do You know how to fix it?

**Comment by BlueRiverInteractive** [comment]
I think we first need to fix this https://github.com/robovm/robovm/issues/679
