### ISSUE TITLE
Touches sample does not compile

### ISSUE THREAD

**Issue by loxal** [robovm/robovm-samples#18]

**Comment by badlogic** [comment]
please post the error message.

**Comment by loxal** [comment]
I’ve created a PR for this simple compile time error.

**Comment by loxal** [comment]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project robovm-samples-touches: Compilation failure: Compilation failure:
[ERROR] /Users/alex/my/project/loxal/robovm-samples/Touches/src/org/robovm/samples/touches/viewcontrollers/TouchViewController.java:[220,39] cannot find symbol
[ERROR] symbol:   method equalToPoint(org.robovm.apple.coregraphics.CGPoint)
[ERROR] location: class org.robovm.apple.coregraphics.CGPoint
[ERROR] /Users/alex/my/project/loxal/robovm-samples/Touches/src/org/robovm/samples/touches/viewcontrollers/TouchViewController.java:[221,42] cannot find symbol
[ERROR] symbol:   method equalToPoint(org.robovm.apple.coregraphics.CGPoint)
[ERROR] location: class org.robovm.apple.coregraphics.CGPoint
[ERROR] /Users/alex/my/project/loxal/robovm-samples/Touches/src/org/robovm/samples/touches/viewcontrollers/TouchViewController.java:[222,43] cannot find symbol
[ERROR] symbol:   method equalToPoint(org.robovm.apple.coregraphics.CGPoint)
[ERROR] location: class org.robovm.apple.coregraphics.CGPoint

**Comment by BlueRiverInteractive** [comment]
All equalToXXX or equalsToXXX methods of Cocoa have been renamed to just equalsTo for simplicity.
Thanks for the PR to fix the sample!

**Comment by loxal** [comment]
Welcome!
