### ISSUE TITLE
Updated instructions

### ISSUE THREAD

**Issue by priand** [robovm/robovm-samples#2]
Thank for the recent update Niklas.
Although I well know Java & Eclipse, I'm actually new to the Mac. So there are a few things that you can add to the instructions to help developers:
- Default max memory (512m) is not enough to compile the samples. It fails with an out of memory error when compiling the JRE dependencies. On Eclipse Mac, this value can be changed in eclipse.ini, located in the application content ('Show Package Content' when you right click the app in the finder), then Contents/MacOS.
- Eclipse can be started with JRE 1.6 even when 1.7 is installed. Typically, you'll get an error stating that the RoboVM plugin failed starting. The JRE to use should be changed in the Info.plist file, located in the application Contents folder. There are some example entries commented out that you should copy and adapt to your own directories. Should look like:
<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java</string>

**Comment by badlogic** [comment]
We've updated this at http://docs.robovm.com.
