### ISSUE TITLE
Don’t use SNAPSHOTs in master branch

### ISSUE THREAD

**Issue by loxal** [robovm/robovm-samples#23]
SNAPSHOTS cannot be validated to work with every example. In fact there were compile errors that came due updated APIs and even if there would be a CI that validates compilation, there could be still subtile runtime errors related to the nature of a SNAPSHOT. 

How about not using SNAPSHOTS but referring to released & *fixed* versions instead?

**Comment by BlueRiverInteractive** [comment]
We depend on version 1.0.0 for now.

**Comment by loxal** [comment]
Depending on a fixed version is perfect but 1.0.0-SNAPSHOT is not fixed, it changes every coupled of days. What compiles today cannot necessarily be compiled tomorrow. Interested devs who want to tryout RoboVM end up checking broken code that might not compile. I just thought it could be an issue worth considering as it does not facilitate the usage of RoboVM.

**Comment by ntherning** [comment]
Totally, agree. From now on we will only depend on proper releases, starting with 1.0.0.

**Comment by loxal** [comment]
@ntherning great, I didn’t noticed you’ve already released v1.0.0. Can’t wait to try it out :)
