### ISSUE TITLE
Add IntelliJ IDEA IDE project meta-data

### ISSUE THREAD

**Issue by loxal** [robovm/robovm-samples#27]
The repository contain Eclipse project meta-data. I’d suggest to add IntelliJ IDEA project meta-data as well which can be completely stored inside the .idea folder at the root level. For the case when the POM is updated and IntelliJ’s files are not, IntelliJ would auto-update the files itself once it knows the structure of the overall project.

**Comment by loxal** [comment]
Actually, this is the complete PR: https://github.com/robovm/robovm-samples/pull/28

**Comment by badlogic** [comment]
I'm working on ensuring that importing the projects via Maven or Gradle works in Intellij IDEA. That way we can get rid of those IDE specific files. I'll try to do the same for Eclipse.

**Comment by badlogic** [comment]
See https://github.com/robovm/robovm-samples/issues/36 for progress
