### ISSUE TITLE
Ensure import of Projects works with Maven/Gradle in IntelliJ IDEA and Eclipse

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-samples#36]

**Comment by ntherning** [comment]
I think you need this one fixed for Eclipse: robovm/robovm-eclipse#49.

**Comment by loxal** [comment]
@badlogic thanks, this would simplify a lot.

**Comment by badlogic** [comment]
Importing via tje root pom into Idea works now. Will get Gradle going asap.

**Comment by badlogic** [comment]
Both Gradle & Maven importing works via IDEA now.

Next up Eclipse.

**Comment by badlogic** [comment]
You can now also import the samples via Maven/Gradle in Eclipse. Requires snapshot 1.2.1 of RoboVM and the RoboVM Eclipse plugin.
