### ISSUE TITLE
Error when executing the sample

### ISSUE THREAD

**Issue by priand** [robovm/robovm-samples#4]
I imported the different samples from GitHub but see the following error in the console.
2014-08-31 17:21:42.637 UICatalog[1568:70b] Application windows are expected to have a root view controller at the end of application launch.
Reported here in SO: http://stackoverflow.com/questions/23981539/robovm-example-code-application-windows-are-expected-to-have-a-root-view-contro

**Comment by BlueRiverInteractive** [comment]
I'll close this as this is just a warning and most of them have already been fixed. When we update the samples to use storyboards this won't be a problem at all.
