### ISSUE TITLE
Make sure ContractR can be imported into IntelliJ

### ISSUE THREAD

**Issue by henricm** [robovm/robovm-samples#51]
Importing ContractR and have all separate projects working would be nice: 
* Android
* iOS
* JavaFX Desktop
* JavaFX iOS.

Currently I managed to get the iOS part to work, but the Android app complains about unsupported gradle version 0.something. 

Tried with IntelliJ CE 14.

**Comment by badlogic** [comment]
This should be fixed. ContractR FX is now a separate (non-functional) project in the root dir.
