### ISSUE TITLE
OSX Desktop Hello World

### ISSUE THREAD

**Issue by rawberg** [robovm/robovm-samples#66]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=26480702)](https://www.bountysource.com/issues/26480702-osx-desktop-hello-world?utm_source=26480702&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Sample "hello world" Mac OSX app. Something to kickstart a community around desktop efforts. Here are some from [Xamarin](https://github.com/xamarin/mac-samples) and [RubyMotion](https://github.com/HipByte/RubyMotionSamples/tree/master/osx) communities.

**Comment by sonuahluwalia** [comment]
Just a confirmation about the task:
You need sample Max OSX apps written in java which are similar to Xamarin's C# Mac applications annd RubyMotion's Ruby Mac applications.
