### ISSUE TITLE
Can you add some method in CustomFrameworks sample using object-c block?

### ISSUE THREAD

**Issue by liaogang** [robovm/robovm-samples#78]

**Comment by liaogang** [comment]
I add a method and got this error:
![2015-11-13 2 13 58](https://cloud.githubusercontent.com/assets/3311527/11140032/f9626f3a-8a10-11e5-8913-0f6e613ae074.png)  
![2015-11-13 2 14 19](https://cloud.githubusercontent.com/assets/3311527/11140031/f91295fa-8a10-11e5-9dd0-aa5f02962649.png)  

    No @Marshaler found for parameter 5 of @Bridge method   
     void      $m$asdf$$$(org.robovm.samples.customframeworks.ObjCAdder,org.robovm.objc.Selector,int,int,org.robovm.objc.block.VoidBlock1)>

**Comment by BlueRiverInteractive** [comment]
There are a few issues with the Method binding.
1. The selector should be `asdf::result:`.
2. You need to annotate a native block with `@Block`.
3. `NSNumber` should be bound as `NSNumber` in Java (not int or Integer).

So your binding should look like:
```Java
@Method(selector = "asdf::result:")
public native void asdf(int a, int b, @Block VoidBlock1<NSNumber> resultBlock);
```

**Comment by liaogang** [comment]
Great,it works

**Comment by liaogang** [comment]
By the way,  how to write binding like this ,  a object-c interface with a category? 
What the class name should be in java?
Can I use Cocoapods to auto build those librarys into static library (xx.a) instead of frameworks(xx.framework)?

@interface UIImageView (WebCache)
- (NSURL *)sd_imageURL;
@end
